### ISSUE TITLE
Backend slows down as soon as frontend is running

### ISSUE THREAD

**Issue by daurer** [SPIhub/hummingbird#53]
The processing rate in MPI mode drops from 110 Hz to 10 Hz as soon as frontend is connected. When I close the GUI, it speeds up again reaching 110 Hz after a couple of seconds.

**Comment by mhantke** [comment]
Do you have image/plot windows opened?

**Comment by daurer** [comment]
I had one image window open. I am trying to reproduce with no plot/image window.

**Comment by daurer** [comment]
Could never be reproduced in real online configuration
